<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" name="Command line test" tests="2" failures="1" timestamp="10 Oct 2016 07:40:43 GMT" time="0.047" errors="0">
  <testcase name="testFail" time="0.014" classname="pkgTest.NewTest">
    <failure type="java.lang.AssertionError" message="expected [This test case if failed.] but found [This test case is failed]">
      <![CDATA[java.lang.AssertionError: expected [This test case if failed.] but found [This test case is failed]
	at pkgTest.NewTest.testFail(NewTest.java:17)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase name="testPass" time="0.0" classname="pkgTest.NewTest"/>
</testsuite> <!-- Command line test -->
